### ISSUE TITLE
Generate Unittest project 

### ISSUE THREAD

**Issue by DominikAmon** [mattwhitfield/Unitverse#113]
First of all: I really dig unitverse for creating unittests. Great job!

Recently I was wondering, if it would be easy to do, to be able to create a new unittest-project by selecting a source-project and a new Option "Create Unittest project for this project". 

Most of the settings, that would be needed are configured anyways, as the function "Generate tests" needs to find the right unittest project. Also the settings, if references, such as Moq, are configured as well.

My 2 cents 😉

**Comment by mattwhitfield** [comment]
So... You would think this would be easy...

The API in Visual Studio for adding projects from templates can only identify templates by their display name - so if you say 'xUnit Unit Test Project' then it works, but only if the user is running Visual Studio in the English language. The API is really designed to be driven by the 'choose project template' dialogue and not a lot else.

Before Unitverse, in the SentryOne generator, creating test projects was a thing - but it did a frustratingly bad job of it.

However, I think I could make something that just writes out the project file directly... Potentially I could add a 'Create new project' option in the test generation dialogue...

As an aside - there were a couple of things I wanted to say to you 😁

1) Thanks for the review on the marketplace, I *really* appreciate it.

2) When the test generation dialogue first got added you wanted to revert to original behaviour. That got me thinking, and I added a 'Generate detached file' item that you can select instead of a target project. I'd be interested to see if that addresses the original concern you had...

Anyway, thanks for the idea - leave it with me. I am just in the middle of writing the StyleCop compatibility stuff, but I will give the project creation another go. 👍

**Comment by mattwhitfield** [comment]
@DominikAmon This is taking some time, apologies. It's mostly research - but one question I haven't found a good answer to is how to reliably get a list of target frameworks. So would it be acceptable, from your point of view, for the created project to have the same target framework as the source project (except for `netstandard*` source projects, which would target `netcoreapp3.1`)?

**Comment by mattwhitfield** [comment]
![image](https://user-images.githubusercontent.com/3195700/167016506-89a0b1fe-5be8-45f5-971d-0d0f6bd3ae3b.png)

**Comment by DominikAmon** [comment]
> So would it be acceptable, from your point of view, for the created project to have the same target framework as the source project (except for `netstandard*` source projects, which would target `netcoreapp3.1`)?

Well, I guess that would be expected behavior, to use the same target framework as the source. On the contrary, wouldn't everything else lead to a version mismatch?

**Comment by mattwhitfield** [comment]
> Well, I guess that would be expected behavior, to use the same target framework as the source. On the contrary, wouldn't everything else lead to a version mismatch?

Well, you could elect to go higher for whatever reason. And people do weird things 🤣

**Comment by mattwhitfield** [comment]
So, a first pass at this is implemented in 0.132. I didn't add it to the 'Generate Test' workflow as yet - it's actually been fairly complex to get it right, so I wanted to push this first and see if it meets your needs.

Basically you can find it by right clicking on a project node and clicking on 'Create unit test project...':
![image](https://user-images.githubusercontent.com/3195700/167188682-db683c70-6d7f-418d-8735-efb2e1d5967c.png)

I'm happy to add this now because it's a completely separate flow, so won't affect core generation in any way... Then, when it's had some time to be proven out I will add it to the documentation and potentially add it into the core generation workflow...

**Comment by mattwhitfield** [comment]
Actually, the publish on 0.132 failed - the marketplace complaining about incompatibility... Bear with me 👍

**Comment by mattwhitfield** [comment]
Ok - 0.133 out now. There's one thing that's a little concerning - which is that Visual Studio can hang if the new project is added and it is still starting up and you time it 'just right'. I don't think it will be a concern in normal usage - but just wanted to mention it - if you come across it please do let me know 👍

**Comment by mattwhitfield** [comment]
@DominikAmon - it's been a while now, so I'm going to close this one out. Any issues please do open up a new issue and thanks for the idea!
