### ISSUE TITLE
Add support for AutoFixture

### ISSUE THREAD

**Issue by chrisw000** [mattwhitfield/Unitverse#126]
**Describe the solution you'd like**
Add support for AutoFixture
https://github.com/AutoFixture/AutoFixture/

and thanks for your tool - awesome!

**Comment by chrisw000** [comment]
Hi, sorry for delay in getting back to you.

I wouldn't say I'm an AutoFixture expert by any stretch of the imagination!

I think a template similar to the end of the quick start example would be an excellent addition:
https://autofixture.github.io/docs/quick-start/#

IE:
Freeze any mocked interfaces are are injected into the constructor of the Sut.
Also inject versions of whatever is the input for the method under test, allowing for them to be further customised?

**Comment by mattwhitfield** [comment]
Ok, so I'm definitely going to have to do this in stages... I did an initial refactor which includes all the plumbing stuff (like detecting whether you are using AutoFixture etc) and value generation and it ended up being much larger than I expected. Basically because I didn't just want to put 'var fixture = new Fixture();' at the top of every test, even if it wasn't going to be needed.

Have a look at https://github.com/mattwhitfield/Unitverse/blob/feature/AutoFixture/docs/examples/ValueGenerationWithAutoFixture.md for an example.

So the next stage is for me to make it behave much like it does with Moq.AutoMoq right now (https://github.com/mattwhitfield/Unitverse/blob/feature/AutoFixture/docs/examples/FrameworksMsTestMoqAutoMock.md) - so it gets the frozen dependencies in the setup method and uses AutoFixture to create the sut.

So I think what I'll do is probably one release with the first stage, and then another release with the second stage (possibly with the ability to configure the behaviour).

Let me know if that makes sense 👍

**Comment by mattwhitfield** [comment]
Ok - so 0.138 is out with the first part 👍

**Comment by chrisw000** [comment]
Nice one - I've downloaded it and can see it starting to amend the output.

Let me know if / when you want some feedback

**Comment by mattwhitfield** [comment]
Any / all feedback gratefully received any time 😁

**Comment by mattwhitfield** [comment]
0.139 is out now and that includes the test class creation / freezing. I *think* I've done it right but honestly not sure. Happy to hear about it either way - so I'll leave this issue open for a few days 👍

**Comment by mattwhitfield** [comment]
^ was a typo, didn't mean to mention this issue 😬

**Comment by mattwhitfield** [comment]
I'm going to close this now, if you do have any feedback or other suggestions, please feel free to open a new issue, and thanks for the suggestion!

**Comment by chrisw000** [comment]
Hi - sorry, I've... been sidetracked with other work... re feedback... will do. thanks!

**Comment by mattwhitfield** [comment]
No worries 👍
