### ISSUE TITLE
XML comments not generated for subsequent generated tests

### ISSUE THREAD

**Issue by Hefaistos68** [mattwhitfield/Unitverse#202]
**The bug**
While XML comments are nicely created when selected in the options of the first run, any subsequently generated tests for other classes have no XML comments. Means, this setting is not persisted.

**To Reproduce**
Take any project with two classes in 2 separate files, create tests for one class, select XML comments, then create tests for the second class. The first has XML comments, the second not.

**Additional context**
C#, VS 2022 17.5.2

**Comment by mattwhitfield** [comment]
I think you might be misunderstanding how settings work - when you select XML comments, you're selecting it for that run only. Try holding down Ctrl the second time you generate tests - it will show the UI again. https://github.com/mattwhitfield/Unitverse/blob/master/docs/configuration.md has some more info on how the settings work...

**Comment by Hefaistos68** [comment]
Yes, you are right. I did not expect it to work like this. TLDR; I did expect that the selection from the first run would apply to subsequent ones, which would make sense from my experience, guess that its not usual to have different kinds in the same test project.
But hey, who reads manuals? Maybe take it as a suggestion then. Or add a "save settings" to the UI?

**Comment by mattwhitfield** [comment]
Yeah - honestly I always try and view this stuff as a UX bug... I'm not sure how best to do it, though. I do totally see how you would have got the impression that the settings applied on an ongoing basis... Let me give it some thought 👍

**Comment by Hefaistos68** [comment]
Maybe really add to the UI the option to save the settings for the current session? I would totally expect this and find it useful. AND also hint to the other settings options in this dialog, this would avoid that "people" stumble over this "problem"

**Comment by mattwhitfield** [comment]
Ok, I've given this some thought, and it's going to look like this (except the checkbox at the bottom will be gone):
![image](https://user-images.githubusercontent.com/3195700/226136713-32ce2fc9-f8b2-4f8f-a19b-f8f24c532e63.png)

It's going to take a little while, though - because that implies that the project mappings could be saved to config files / vs settings - which they can't currently. So there's a bit of work to do in order to allow that. 👍

**Comment by Hefaistos68** [comment]
That looks pretty good. Can't wait to test. But no hurry, am busy with enough.

**Comment by mattwhitfield** [comment]
Ok, I just merged this, so it is now available in 0.187.

There's a couple of new concepts introduced by this (which is why I created a follow up item to work on docs):

* The ability to define permanent test project mappings - so you can specify source -> target mappings which will take precedence over the automatic targeting. You can define those in the VS Options dialog, in config files or store them for the session (until VS closes).
* The concept of session settings - this did previously exist for project mappings but not other settings. You can now (as the bug suggests) modify a setting and have it apply until VS closes. As a bonus, you can also persist those settings to config files, or update the VS Options.

So I think it's in a much better place now both in terms of flexibility and making the behaviour more obvious.

Definitely interested to hear your thoughts 👍

I'll probably get to the documentation updates later this week.

**Comment by mattwhitfield** [comment]
Ok, well, going to close this now - feel free to re-open if you have any issues 👍
