### ISSUE TITLE
Add ability to skip internal types when generating for multiple types

### ISSUE THREAD

**Issue by mattwhitfield** [mattwhitfield/Unitverse#225]
If you are generating for multiple types, all potential types will have tests generated for them. We would like to add the ability to skip internal types during this process.

**Comment by shshshshgoodnj** [comment]
I owe you for your services.
I hope you can skip the TC generation of the internal class. 
Thank you:)

**Comment by mattwhitfield** [comment]
This should be available in 0.195 👍 Under 'Generation Options' there is 'Skip internal types on multiple generation' (SkipInternalTypesOnMultipleGeneration in a config file)

**Comment by mattwhitfield** [comment]
The logic is currently:

If we are generating for more than one source file and the option is enabled, skip internal types

There is an edge case - if one source file has 50 types in it, then it wouldn't filter internal types...

Interested to hear your thoughts on that.

The reason it doesn't always skip them, is because if people right click on a single file and click 'generate tests' but nothing happens then it can be confusing.

**Comment by shshshshgoodnj** [comment]
It applies well. Thank you :)

**Comment by shshshshgoodnj** [comment]
Hello, I'm a user who uses Unitverse that you created.

I downloaded the open source because I wanted to check the open source while using Unitverse, but the Unitverse project is not compatible with VS2019.
I can't use VS2022 because it's not licensed, is there a way to check Unitverse open source with VS2019?
I referred to the picture.



I'd appreciate it if you could reply :)
