### ISSUE TITLE
Report some errors

### ISSUE THREAD

**Issue by endend789** [mattwhitfield/Unitverse#232]
1. After installing the moq, autofixture, and autofixture.moq package, some failures occurs.
Failures dont occur because you did not set the assert, but it fails when you call autofixure.
![image](https://github.com/mattwhitfield/Unitverse/assets/114501864/e68a3861-a824-40f4-a132-f229428c72e1)

2. After modifying the settings of visual studio 2022 as shown below, when generating the test case of the project using Unitverse,
In the Unitverse options window, 'use Autofixture', 'use autofixture for mocking' is checked as shown below,
even though I set False in the visual studio setting.
![image](https://github.com/mattwhitfield/Unitverse/assets/114501864/7e950101-959c-4efb-8272-40bd6c5edb78)
![image](https://github.com/mattwhitfield/Unitverse/assets/114501864/862acd8c-0ff3-4e8b-9877-d85fc65b717b)

3. TCs are also created for methods set as class internal private.
![image](https://github.com/mattwhitfield/Unitverse/assets/114501864/f4d83797-e6a6-4f33-9c2f-e2c22be288a7)
(this method is private one.)
![image](https://github.com/mattwhitfield/Unitverse/assets/114501864/12c37612-8818-436b-b934-02f7936228a0)

When TC is generated for methods and variables set to private, an error CS2022 occurs.
Is there a function that does not create TCs for private? Then tell me how to do it.
If you don't have the function, can you add the function?

**Comment by mattwhitfield** [comment]
So for 1) I think that is an auto fixture issue from the sounds of it.

For 2) the magnifying glass icon next to the options in the generation dialog means that it enabled that option because it examined the references present in the target project, found auto fixture and so assumed you wanted to use it. There is an option to turn off automatic framework detection.

For 3) it should, if the constructor is private, try and find a method or property that is static and returns the type in question. Try it - and if that isn't the case then please do post a fuller repro.

Thanks!

**Comment by mattwhitfield** [comment]
Going to close this now, as it seems like it's working OK and I can't repro the behavior described in point 3. If you do manage to get a repro for it, please feel free to open another issue. Cheers!
