### ISSUE TITLE
No Test Generated for Inherited method

### ISSUE THREAD

**Issue by CoenraadS** [mattwhitfield/Unitverse#241]
**Describe the bug**

When generating a test for a class that inherits a method, I expect a test for that method.

**To Reproduce**

```
public abstract class Test
{
    public void Render(StringBuilder sb)
    {

    }
}

public sealed class Test2 : Test
{

}
```

Trying to generate test for class Test2 results in:

![image](https://github.com/mattwhitfield/Unitverse/assets/5593825/44cbee5c-3551-4f71-b686-683fffa95fd1)

[config.txt](https://github.com/mattwhitfield/Unitverse/files/14186758/config.txt)

**Comment by mattwhitfield** [comment]
It is actually designed like that - because the behaviour isn't in the inheriting class. So, in general, tests are emitted for things defined in the class you are generating for, and not elsewhere...

Should every class emit a test for the ToString method, for example?

Happy to add an option that makes it behave differently - but interested to hear your thoughts on exactly what it should do - especially when the methods that you are inheriting are defined in a different assembly.

**Comment by CoenraadS** [comment]
I understand, I think I will rework my class to use less inheritance, wasn't really a fan of what I was doing anyway.. :)
